### All Users
GET http://localhost:8080/api/users


### Single User by ID w/o req.query
GET http://localhost:8080/api/users/1
Content-Type: application/json


### Single User by ID with req.query.read = true
GET http://localhost:8080/api/users/1?read=true
Content-Type: application/json


### Single User by ID with req.query.read = true
GET http://localhost:8080/api/users/1?read=false
Content-Type: application/json


### Signup
POST http://localhost:8080/api/users/signup
Content-Type: application/json


{
    "username": "user2@example.io",
    "name": "Juan Dela Cruz",
    "password": "password2%"
}

### Login
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
    "username": "user2@example.io",
    "password": "password2%"
}

### Update Single by username req.params
PATCH http://localhost:8080/api/users/user1@example.io
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODAyMjEzOTMsImV4cCI6MTY4MDIyNDk5MywiYXVkIjoiMSIsImlzcyI6ImFybmVsaW1wZXJpYWwuY29tIn0.EiqEUmdv03Op_XV_76QGjOR9Fxre2Y6WI1NeOUj4Do4

{
    "username": "user2@example.io",
    "name": "Boyd K. Montgomery",
    "password": "password2#"
   
}


### Logout
DELETE http://localhost:8080/api/users/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODAyMzEzNjYsImV4cCI6MTY4MDIzNDk2NiwiYXVkIjoiMSIsImlzcyI6ImFybmVsaW1wZXJpYWwuY29tIn0.VuYWpzRTNFCAvmYo9bx4u1kQc-d_gTbV5gwsPd-8Wng


### Request new access token using refresh token as req.body
POST http://localhost:8080/api/users/auth-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODAyMDc4MzgsImV4cCI6MTY4MDIxMTQzOCwiYXVkIjoiMSIsImlzcyI6ImFybmVsaW1wZXJpYWwuY29tIn0.nw8L4CzT5mXvbiYx8mDQdDYuAVFhJCZi2uzj5DZURc4

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODAyMDc4MzgsImV4cCI6MTY4Mjc5OTgzOCwiYXVkIjoiMSIsImlzcyI6ImFybmVsaW1wZXJpYWwuY29tIn0.5ClMUHgz9KHRw66pURPKk7VxIMX3pOzEVkDqVvPxRrw"
}



### All Blogs w/o req.query.search
GET http://localhost:8080/api/blogs


### All Blogs with req.query.search (Search for title & author field)
GET http://localhost:8080/api/blogs?search=TDD Harms Architecture



### Single blog by ID
GET http://localhost:8080/api/blogs/blog/2


### Create blog
POST http://localhost:8080/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODAyODE4MzksImV4cCI6MTY4MDI4NTQzOSwiYXVkIjoiMSIsImlzcyI6ImFybmVsaW1wZXJpYWwuY29tIn0.KcOQYnB_S94fttzZjEAd0TVTS_Yp1ej7MnoFS_eOiCc

{
    
    "title": "TDD Harms Architecture I",
    "url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
    "author": "Robert C. Martin I",
    "likes": 1,
    "year": 2000
}

### Update blog by ID
PUT http://localhost:8080/api/blogs/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODAyMjQ3MjYsImV4cCI6MTY4MDIyODMyNiwiYXVkIjoiMSIsImlzcyI6ImFybmVsaW1wZXJpYWwuY29tIn0.c8DhWwH0pJVAZP1sVBx5Sc8cmXvEJ2pOuQDUNbgHMXg

{
    
    "title": "TDD Harms Architecture",
    "url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
    "author": "Robert C. Martin",
    "likes": 9,
    "year": 2004
}


### Delete blog by ID
DELETE  http://localhost:8080/api/blogs/omit/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODAyMjIyNDEsImV4cCI6MTY4MDIyNTg0MSwiYXVkIjoiMSIsImlzcyI6ImFybmVsaW1wZXJpYWwuY29tIn0.kQpbbO3-G15wIs-Nn2ma5MuJ-Irs41l4Dy6k5e4sLsI


### Aggregate blogs by author field
GET http://localhost:8080/api/authors


### List readings
GET http://localhost:8080/api/readinglists


### Retrieve reading by ID
GET http://localhost:8080/api/readinglists/retrieve/2


### Update reading by ID
PATCH http://localhost:8080/api/readinglists/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODAyODE4MzksImV4cCI6MTY4MDI4NTQzOSwiYXVkIjoiMSIsImlzcyI6ImFybmVsaW1wZXJpYWwuY29tIn0.KcOQYnB_S94fttzZjEAd0TVTS_Yp1ej7MnoFS_eOiCc

{
    "read": true
}