### All Users
GET http://localhost:8080/api/users

### Single User
GET http://localhost:8080/api/users/1
Content-Type: application/json


### Signup
POST http://localhost:8080/api/users/signup
Content-Type: application/json

{
    "username": "user1@example.io",
    "name": "Juan Dela Cruz",
    "password": "password1%"
}


### Login
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
    "username": "user1@example.io",
    "password": "password1%"
}


### Update Single User with username params
PATCH http://localhost:8080/api/users/user1@example.io
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODAyMjEzOTMsImV4cCI6MTY4MDIyNDk5MywiYXVkIjoiMSIsImlzcyI6ImFybmVsaW1wZXJpYWwuY29tIn0.EiqEUmdv03Op_XV_76QGjOR9Fxre2Y6WI1NeOUj4Do4

{
    "username": "user2@example.io",
    "name": "Boyd K. Montgomery",
    "password": "password2#"
   
}


### Logout
DELETE http://localhost:8080/api/users/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODAyMjEzOTMsImV4cCI6MTY4MDIyNDk5MywiYXVkIjoiMSIsImlzcyI6ImFybmVsaW1wZXJpYWwuY29tIn0.EiqEUmdv03Op_XV_76QGjOR9Fxre2Y6WI1NeOUj4Do4


### Request new access token
POST http://localhost:8080/api/users/auth-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODAyMDc4MzgsImV4cCI6MTY4MDIxMTQzOCwiYXVkIjoiMSIsImlzcyI6ImFybmVsaW1wZXJpYWwuY29tIn0.nw8L4CzT5mXvbiYx8mDQdDYuAVFhJCZi2uzj5DZURc4

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODAyMDc4MzgsImV4cCI6MTY4Mjc5OTgzOCwiYXVkIjoiMSIsImlzcyI6ImFybmVsaW1wZXJpYWwuY29tIn0.5ClMUHgz9KHRw66pURPKk7VxIMX3pOzEVkDqVvPxRrw"
}

### All Blogs
GET http://localhost:8080/api/blogs

### Single blog
GET http://localhost:8080/api/blogs/blog/1

### Create blog
POST http://localhost:8080/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODAyMjY2MzMsImV4cCI6MTY4MDIzMDIzMywiYXVkIjoiMSIsImlzcyI6ImFybmVsaW1wZXJpYWwuY29tIn0.EfrvWOd4MTJ6gXNmuYrHcthmFidMnuLUhapF5FceMoM

{
    
    "title": "TDD Harms Architecture",
    "url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
    "author": "Robert C. Martin",
    "likes": 7,
    "year": 2000
}

### Update blog
PUT http://localhost:8080/api/blogs/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODAyMjQ3MjYsImV4cCI6MTY4MDIyODMyNiwiYXVkIjoiMSIsImlzcyI6ImFybmVsaW1wZXJpYWwuY29tIn0.c8DhWwH0pJVAZP1sVBx5Sc8cmXvEJ2pOuQDUNbgHMXg

{
    
    "title": "TDD Harms Architecture",
    "url": "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
    "author": "Robert C. Martin",
    "likes": 9,
    "year": 2004
}


### Delete blog
DELETE  http://localhost:8080/api/blogs/omit/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODAyMjIyNDEsImV4cCI6MTY4MDIyNTg0MSwiYXVkIjoiMSIsImlzcyI6ImFybmVsaW1wZXJpYWwuY29tIn0.kQpbbO3-G15wIs-Nn2ma5MuJ-Irs41l4Dy6k5e4sLsI

### Authors
GET http://localhost:8080/api/authors

### List readings
GET http://localhost:8080/api/readinglists

### Retrieve reading by ID
GET http://localhost:8080/api/readinglists/retrieve/1


### Update Reading lists 
PATCH http://localhost:8080/api/readinglists/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODAyMjUxNTksImV4cCI6MTY4MDIyODc1OSwiYXVkIjoiMSIsImlzcyI6ImFybmVsaW1wZXJpYWwuY29tIn0.-ItJo-Gz51GB5QveDUnGs-ziU4CTcFAxsSujzJajsEA

{
    "read": true
}